# ------------------------------------------------------------------------------
# VRF and Network Configuration for NDFC
# ------------------------------------------------------------------------------
# This file contains the VRF (Virtual Routing and Forwarding) and network 
# configurations that will be provisioned in Cisco NDFC.
#
# It includes:
# - **VRFs**: Defines Virtual Routing and Forwarding instances with VLAN IDs.
# - **Networks**: Defines Layer 2 and Layer 3 network segments associated with VRFs.
#
# These configurations enable network segmentation and policy enforcement 
# within the NDFC-managed fabric.
# ------------------------------------------------------------------------------

# ---------------------------------------------------------------- #
# VRF Configuration                                                #
# ---------------------------------------------------------------- #
# Each VRF has an associated VLAN ID and is attached to all leaf switches.
vrfs:
- vrf_name: mgs-in
  vrf_id: 101100
  vlan_id: 1100
  attach_group: all_leaf
  deploy: false
- vrf_name: infra
  vrf_id: 100103
  vlan_id: 103
  attach_group: all_leaf
  deploy: false
- vrf_name: internet
  vrf_id: 101500
  vlan_id: 1500
  attach_group: all_leaf
  deploy: false

# ---------------------------------------------------------------- #
# Network Configuration                                            #
# ---------------------------------------------------------------- #
# Each network is identified by:
# - A name (`net_name`)
# - The associated VRF (`vrf_name`)
# - A unique network ID (`net_id`)
# - A VLAN ID (`vlan_id`)
# - Gateway IP and subnet (`gw_ip_subnet`)
# - The attachment group defining where it is deployed (`attach_group`)
# - Additional attributes like MTU size and interface descriptions.
networks:
- net_name: l2ext-svc-cp
  vrf_name: mgs-in
  net_id: 201100
  vlan_id: 1100
  gw_ip_subnet: 10.67.0.1/26
  attach_group: esxi
  deploy: false
  vlan_name: svc-cp
  mtu_l3intf: 9000.0
  int_desc: svc-cp
- net_name: aead3-svc-worker
  vrf_name: mgs-in
  net_id: 210111
  vlan_id: 111
  gw_ip_subnet: 10.64.136.129/26
  attach_group: esxi
  deploy: false
  vlan_name: svc-worker
  mtu_l3intf: 9000.0
  int_desc: svc-worker
- net_name: aead3-svc-sdc-data-1
  vrf_name: infra
  net_id: 210103
  vlan_id: 103
  gw_ip_subnet: 10.64.70.1/26
  attach_group: esxi
  deploy: false
  vlan_name: svc-sdc-data-1
  mtu_l3intf: 9000.0
  int_desc: svc-sdc-data-1
- net_name: aead3-svc-sdc-data-2
  vrf_name: infra
  net_id: 210105
  vlan_id: 105
  gw_ip_subnet: 10.64.71.1/26
  attach_group: esxi
  deploy: false
  vlan_name: svc-sdc-data-2
  mtu_l3intf: 9000.0
  int_desc: svc-sdc-data-2
- net_name: aead3-hsm-mgmt
  vrf_name: mgs-in
  net_id: 210114
  vlan_id: 114
  gw_ip_subnet: 10.64.136.1/27
  attach_group: esxi
  deploy: false
  vlan_name: hsm-mgmt
  mtu_l3intf: 9000.0
  int_desc: hsm-mgmt
- net_name: aead3-hsm-data
  vrf_name: mgs-in
  net_id: 210115
  vlan_id: 115
  gw_ip_subnet: 10.64.136.33/27
  attach_group: esxi
  deploy: false
  vlan_name: hsm-data
  mtu_l3intf: 9000.0
  int_desc: hsm-data
- net_name: aead3-svc-obs-mgmt
  vrf_name: mgs-in
  net_id: 210116
  vlan_id: 116
  gw_ip_subnet: 10.64.136.65/28
  attach_group: esxi
  deploy: false
  vlan_name: svc-obs-mgmt
  mtu_l3intf: 9000.0
  int_desc: svc-obs-mgmt
- net_name: aead3-svc-idm
  vrf_name: mgs-in
  net_id: 210113
  vlan_id: 113
  gw_ip_subnet: 10.64.136.97/28
  attach_group: esxi
  deploy: false
  vlan_name: svc-idm
  mtu_l3intf: 9000.0
  int_desc: svc-idm
- net_name: l2ext-rhoso-ocp-cp
  vrf_name: mgs-in
  net_id: 201101
  vlan_id: 1101
  gw_ip_subnet: 10.67.0.65/26
  attach_group: esxi
  deploy: false
  vlan_name: rhoso-ocp-cp
  mtu_l3intf: 9000.0
  int_desc: rhoso-ocp-cp
- net_name: aead3-rhoso-ocp-worker
  vrf_name: mgs-in
  net_id: 210112
  vlan_id: 112
  gw_ip_subnet: 10.64.136.193/26
  attach_group: esxi
  deploy: false
  vlan_name: rhoso-ocp-worker
  mtu_l3intf: 9000.0
  int_desc: rhoso-ocp-worker
- net_name: aead3-rhoso-sdc-data-1
  vrf_name: infra
  net_id: 210104
  vlan_id: 104
  gw_ip_subnet: 10.64.70.65/26
  attach_group: esxi
  deploy: false
  vlan_name: rhoso-sdc-data-1
  mtu_l3intf: 9000.0
  int_desc: rhoso-sdc-data-1
- net_name: aead3-rhoso-sdc-data-2
  vrf_name: infra
  net_id: 210106
  vlan_id: 106
  gw_ip_subnet: 10.64.71.65/26
  attach_group: esxi
  deploy: false
  vlan_name: rhoso-sdc-data-2
  mtu_l3intf: 9000.0
  int_desc: rhoso-sdc-data-2
- net_name: l2ext-osp-mgmt-cp
  vrf_name: mgs-in
  net_id: 201102
  vlan_id: 1102
  gw_ip_subnet: 10.67.1.1/24
  attach_group: esxi
  deploy: false
  vlan_name: osp-mgmt-cp
  mtu_l3intf: 9000.0
  int_desc: osp-mgmt-cp
- net_name: l2ext-osp-mgmt-int-api
  vrf_name: mgs-in
  net_id: 201103
  vlan_id: 1103
  gw_ip_subnet: 10.67.2.1/23
  attach_group: esxi
  deploy: false
  vlan_name: osp-mgmt-int-api
  mtu_l3intf: 9000.0
  int_desc: osp-mgmt-int-api
- net_name: l2ext-osp-mgmt-tenant
  vrf_name: infra
  net_id: 201104
  vlan_id: 1104
  gw_ip_subnet: 10.67.35.1/24
  attach_group: esxi
  deploy: false
  vlan_name: osp-mgmt-tenant
  mtu_l3intf: 9000.0
  int_desc: osp-mgmt-tenant
- net_name: l2ext-osp-mgmt-log-forward
  vrf_name: infra
  net_id: 201106
  vlan_id: 1106
  gw_ip_subnet: 10.67.33.1/24
  attach_group: esxi
  deploy: false
  vlan_name: osp-mgmt-log-forward
  mtu_l3intf: 9000.0
  int_desc: osp-mgmt-log-forward
- net_name: l2ext-osp-mgmt-trilio-backup
  vrf_name: infra
  net_id: 201107
  vlan_id: 1107
  gw_ip_subnet: 10.67.34.1/24
  attach_group: esxi
  deploy: false
  vlan_name: osp-mgmt-trilio-backup
  mtu_l3intf: 9000.0
  int_desc: osp-mgmt-trilio-backup
- net_name: aead3-osp-nws-cp
  vrf_name: infra
  net_id: 210260
  vlan_id: 260
  gw_ip_subnet: 10.64.80.1/27
  attach_group: esxi
  deploy: false
  vlan_name: osp-nws-cp
  mtu_l3intf: 9000.0
  int_desc: osp-nws-cp
- net_name: aead3-osp-nws-int-api
  vrf_name: infra
  net_id: 210261
  vlan_id: 261
  gw_ip_subnet: 10.64.80.33/27
  attach_group: esxi
  deploy: false
  vlan_name: osp-nws-int-api
  mtu_l3intf: 9000.0
  int_desc: osp-nws-int-api
- net_name: aead3-osp-nws-tenant
  vrf_name: infra
  net_id: 210262
  vlan_id: 262
  gw_ip_subnet: 10.64.80.65/27
  attach_group: esxi
  deploy: false
  vlan_name: osp-nws-tenant
  mtu_l3intf: 9000.0
  int_desc: osp-nws-tenant
- net_name: aead3-osp-nws-trilio-backup
  vrf_name: infra
  net_id: 210263
  vlan_id: 263
  gw_ip_subnet: 10.64.80.97/27
  attach_group: esxi
  deploy: false
  vlan_name: osp-nws-trilio-backup
  mtu_l3intf: 9000.0
  int_desc: osp-nws-trilio-backup
- net_name: aead3-osp-nws-log-forward
  vrf_name: infra
  net_id: 210264
  vlan_id: 264
  gw_ip_subnet: 10.64.80.129/27
  attach_group: esxi
  deploy: false
  vlan_name: osp-nws-log-forward
  mtu_l3intf: 9000.0
  int_desc: osp-nws-log-forward
- net_name: l2ext-osp-internet
  vrf_name: internet
  net_id: 201500
  vlan_id: 1500
  gw_ip_subnet: 77.242.253.1/24
  attach_group: esxi
  deploy: false
  vlan_name: osp-internet
  mtu_l3intf: 9000.0
  int_desc: osp-internet
- net_name: aead3-osp-com-cp
  vrf_name: infra
  net_id: 210202
  vlan_id: 202
  gw_ip_subnet: 10.64.0.1/22
  attach_group: esxi
  deploy: false
  vlan_name: osp-com-cp
  mtu_l3intf: 9000.0
  int_desc: osp-com-cp
- net_name: aead3-osp-com-int-api
  vrf_name: infra
  net_id: 210203
  vlan_id: 203
  gw_ip_subnet: 10.64.4.1/22
  attach_group: esxi
  deploy: false
  vlan_name: osp-com-int-api
  mtu_l3intf: 9000.0
  int_desc: osp-com-int-api
- net_name: aead3-osp-com-tenant
  vrf_name: infra
  net_id: 210204
  vlan_id: 204
  gw_ip_subnet: 10.64.8.1/22
  attach_group: esxi
  deploy: false
  vlan_name: osp-com-tenant
  mtu_l3intf: 9000.0
  int_desc: osp-com-tenant
- net_name: aead3-osp-sdc-data-1
  vrf_name: infra
  net_id: 210200
  vlan_id: 200
  gw_ip_subnet: 10.64.72.1/22
  attach_group: esxi
  deploy: false
  vlan_name: osp-sdc-data-1
  mtu_l3intf: 9000.0
  int_desc: osp-sdc-data-1
- net_name: aead3-osp-sdc-data-2
  vrf_name: infra
  net_id: 210201
  vlan_id: 201
  gw_ip_subnet: 10.64.76.1/22
  attach_group: esxi
  deploy: false
  vlan_name: osp-sdc-data-2
  mtu_l3intf: 9000.0
  int_desc: osp-sdc-data-2
- net_name: aead3-osp-com-trilio-backup
  vrf_name: infra
  net_id: 210205
  vlan_id: 205
  gw_ip_subnet: 10.64.12.1/22
  attach_group: esxi
  deploy: false
  vlan_name: osp-com-trilio-backup
  mtu_l3intf: 9000.0
  int_desc: osp-com-trilio-backup
- net_name: aead3-osp-com-log-forward
  vrf_name: infra
  net_id: 210206
  vlan_id: 206
  gw_ip_subnet: 10.64.16.1/22
  attach_group: esxi
  deploy: false
  vlan_name: osp-com-log-forward
  mtu_l3intf: 9000.0
  int_desc: osp-com-log-forward
