download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cisco-dcnm-3.6.0.tar.gz
format_version: 1.0.0
name: dcnm
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.6.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/cisco/dcnm/versions/3.6.0/
